name: Build and Deploy Quarkus JVM Image
description: Build and deploy Quarkus JVM image to DockerHub
inputs:
  image-name:
    description: Docker image name
    required: true
  image-tag:
    description: Docker image tag
    required: true
outputs: {}
runs:
  using: 'composite'
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Log in to Dockerhub
      uses: docker/login-action@v3
      with:
          username: ${{ inputs.reg-userneame }}
          password: ${{ inputs.reg-token }}
    - name: Build Quarkus JVM Image
      shell: sh
      run: |
        ./gradlew clean assemble \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.name=${{ inputs.image-name }} \
          -Dquarkus.container-image.tag=${{ inputs.image-tag }} \
          -Dquarkus.container-image.username=${{ inputs.reg-userneame }} \
          -Dquarkus.container-image.password=${{ inputs.reg-token }}
