name: Build and Deploy Quarkus Native Image
description: Build and deploy Quarkus native image to DockerHub
inputs:
  image-name:
    description: Docker image name
    required: true
  image-tag:
    description: Docker image tag
    required: true
  reg-username:
    description: image registry username
    required: true
  reg-token:
    description: image registry token
    required: true
outputs: {}
runs:
  using: 'composite'
  steps:
    - name: Set up graalvm
      uses: actions/setup-java@v4
      with:
          distribution: 'graalvm'
          java-version: '21'
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ inputs.reg-username }}
          password: ${{ inputs.reg-token }}
    - name: Build Quarkus Native Image
      shell: sh
      run: |
        ./gradlew clean assemble \
          -Dquarkus.package.type=native \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.name=${{ inputs.image-name }} \
          -Dquarkus.container-image.tag=${{ inputs.image-tag }} \
          -Dquarkus.native.additional-build-args="--initialize-at-run-time=org.apache.kafka.common.security.authenticator.SaslClientAuthenticator\,org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin" \
          
    # -Dquarkus.container-image.username=${{ secrets.DOCKERHUB_USERNAME }} \
          #-Dquarkus.container-image.password=${{ secrets.DOCKERHUB_PASSWORD }}
